name: dox-compose
root: <%= ENV["PROJECT_DIR"] %>/dox-compose
# needed for pane-base-index 1 config
startup_pane: 1

# Runs on project start, always
on_project_start: git pull origin master; bin/dox-dc up -d network-frontend

# Run on project start, the first time
on_project_first_start: bin/dox-update

# Run on project stop
on_project_stop: dox-dc down; docker-sync stop

# Controls whether the tmux session should be attached to automatically
attach: false

# Specifies (by name or index) which window will be selected on project startup
startup_window: containers

windows:
  - editor:
      layout: main-horizontal
      panes:
        - vim .
        -
  - containers:
      layout: tiled
      panes:
        # Auth API
        - dox-dc build auth-api && dox-dc up auth-api
        # Kafka
        - dox-dc up kafka
        # ElasticSearch
        - dox-dc up elasticsearch
        # Neo4j
        - dox-dc up neo4j
        # Bridge DB
        - dox-dc up bridge-schema-database
