# This file loads in non-interactive shells
# I've found that using this file slows down the shell, specifically
# vim-tmux navigation. Instead, favor zshrc.

# Load all .zshenv config files in this dir
# aliases.zshenv should be available in all shells, not just interactive ones.
# Ie. vim should have aliases

export ZSH=$HOME/.oh-my-zsh # Path to your oh-my-zsh installation.
export PROJECT_DIR=$HOME/GitHubRepos
export DOTFILES_DIR=$PROJECT_DIR/dotfiles
export DROPBOX_DIR=$HOME/Dropbox

for file in "$DOTFILES_DIR"/mac/zsh/*.zshenv; do
  source "$file"
done

### PYENV and Python - https://github.com/pyenv/pyenv#homebrew-on-mac-os-x ###
# Step #3 here says to place in zshenv rather than zshrc
# https://github.com/pyenv/pyenv#basic-github-checkout
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# https://github.com/rbenv/rbenv/issues/142
eval "$(rbenv init -)"
